# Various configs

# Sound paths in development and production environments
sound_path_development = "/home/bt/Dropbox/jungle.horse/sounds"
sound_path_production = "./sounds"

# Complete path to the phoneme dictionary file
phoneme_dictionary_file_development = "./dictionary/cmudict-0.7b"
phoneme_dictionary_file_production = "./dictionary/cmudict-0.7b"

