
# Configs for the server.

[default] # Production
  use_caching_headers = false
  sound_path = "./sounds"
  phoneme_dictionary_file = "./dictionary/cmudict-0.7b"
  extra_dictionary_file = "./dictionary/extra-dict"
  square_dictionary_file = "./dictionary/square-dict"

[x16] # Local Development
  use_caching_headers = false
  sound_path = "/home/bt/Dropbox/jungle.horse/sounds"

