# Various configs

# TODO: This 'hostname' key is present only as a hack.
# Stop writing bad code, Brandon.
hostname = ""

# Whether or not to read the "If-None-Match" headers.
# Turn this off for development and on for production.
use_caching_headers = false

# Sound paths in development and production environments
sound_path_development = "/home/bt/Dropbox/jungle.horse/sounds"
sound_path_production = "./sounds"

# Complete path to the phoneme dictionary file
phoneme_dictionary_file_development = "./dictionary/cmudict-0.7b"
phoneme_dictionary_file_production = "./dictionary/cmudict-0.7b"
extra_dictionary_file_development = "./dictionary/extra-dict"
extra_dictionary_file_production = "./dictionary/extra-dict"
square_dictionary_file_development = "./dictionary/square-dict"
square_dictionary_file_production = "./dictionary/square-dict"

