
# Hide sourcemaps in production
[build.environment]
GENERATE_SOURCEMAP = "true"
[build.production.environment]
GENERATE_SOURCEMAP = "false"

[context.production]
environment = { GENERATE_SOURCEMAP = "false" }
#GENERATE_SOURCEMAP=false

