# A list of statically-configured (not-DB backed) API tokens.
# This file is not distributed with the docker image and is just an example for local development.

#[[api_tokens]]
#api_token = 'foo'
#maybe_user_token = 'FOO'
#maybe_priority_level = 3

# /profile/api_edymuro (EdyMuro#8205)
# Requested 2022-04-18 in Discord chat with Vegito
# Using for their own mobile TTS app.
[[api_tokens]]
api_token = "SAPI:EDYMURO_A648684D5C6FDCFD"
maybe_user_token = 'U:VR4HNTYCDBR9W'

# /profile/api_ftk789 (ftk789#7898)
# Twitch TTS / Moderator
# Requested 2022-04-27
[[api_tokens]]
api_token = "SAPI:FTK789_6096133E1D79D6FB"
maybe_user_token = 'U:0S09H086R6TRH'
