# --------------- Tacotron ---------------

# TODO: Get a high-quality LJS Tacotron

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-02-06_ckpt30000.jit"
description = "First Trump txlearn with Arpabet. Trained 30k iters and sounds great!"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-14_ckpt7000.jit"
description = "Trump txlearn with Arpabet 2020-05-14"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-14_ckpt11500.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-14_ckpt17000.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-14_ckpt27000.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-14_ckpt27000-18000.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-14_ckpt53500.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-14_chkpt112500.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-23_chkpt8000.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-23_chkpt13000.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-24_chkpt2000.jit"
description = "Trump txlearn with Arpabet 2020-05-24; adds 400 new training files from steno"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-24_chkpt16000.jit"
description = "(see previous)"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-25_chkpt7000.jit"
description = "Trump txlearn with Arpabet 2020-05-25; adds lots from steno, disabled one bad quality source"

[[tacotron]]
file_path = "/data/models/tacotron2-nvidia/tacotron2_trump_txlearn_ljs_arpabet_2020-05-25_chkpt17000.jit"
description = "(see previous)"


# ======== OLDER RUNS ======

[[tacotron]]
# OLD NAME, perhaps I can get the epoch: file_path = "/data/models/tacotron2-nvidia/tacotron_arpabet_1.pt"
file_path = "/data/models/tacotron2-nvidia/tacotron2_ljs_high_pitch_arpabet_2020-03-28.jit"
description = "High-quality high-pitched LJS; arpabet encodings."

# [[tacotron]]
# # TODO: Remove. This blows up.
# file_path = "/data/models/tacotron2-nvidia/tacotron_container.pt"
# description = "Unknown (broken)"
# 
# [[tacotron]]
# # TODO: Remove. This hangs forever.
# file_path = "/data/models/tacotron2-nvidia/tacotron_jit_model_voder_c0cac635.pt"
# description = "Unknown (broken)"


# ---------------- Melgan ----------------

# TODO: Get a high-quality LJS Melgan

[[melgan]]
file_path = "/data/models/melgan-swpark/melgan_trump-txlearn-2020.05.05_7525.jit"
description = "Latest LJS transfer learned Trump."

[[melgan]]
file_path = "/data/models/melgan-swpark/melgan_trump-txlearn-2020.05.05_13675.jit"
description = "Latest LJS transfer learned Trump."

[[melgan]]
file_path = "/data/models/melgan-swpark/melgan_ljs-high-pitch_container.pt"
description = "High-pitched LJS"

[[melgan]]
file_path = "/data/models/melgan-swpark/shared_melgan_container-2020.01.04.pt"
description = "Unknown"

[[melgan]]
file_path = "/data/models/melgan-swpark/shared_melgan_container-2020.01.05.pt"
description = "Unknown"

