# --------------- Speakers: Trumped.com ---------------
[[speakers]]
name = "Donald Trump"
slug = "trump"
model_pipeline = "ArpabetGlowTtsMelgan"
melgan = "melgan_trump_txlearn_2020-05-30_steno_chkpt9800.torchjit"
glow_tts = "glow_tts_ljs_txlearn_arpabet_2020-06-01_G_1689-2.torchjit"

# --------------- Speakers: Vo.codes  ---------------
[[speakers]]
name = "Donald Trump (Multi-speaker model)"
slug = "glow-multi-trump"
model_pipeline = "ArpabetGlowTtsMultiSpeakerMelgan"
glow_tts_multi_speaker = "glow_tts_multispeaker_8-speaker_256-gin_ljs_txlearn_2020.06.19_experiment-5_chkpt-7466.torchjit"
melgan = "melgan_vocodes1.0_multispeaker_2020.06.19_12d5838_experiment-2_chkpt-10400.torchjit"
speaker_id = 0

[[speakers]]
name = "John Oliver (Multi-speaker model)"
slug = "glow-multi-oliver"
model_pipeline = "ArpabetGlowTtsMultiSpeakerMelgan"
glow_tts_multi_speaker = "glow_tts_multispeaker_8-speaker_256-gin_ljs_txlearn_2020.06.19_experiment-5_chkpt-7466.torchjit"
melgan = "melgan_vocodes1.0_multispeaker_2020.06.19_12d5838_experiment-2_chkpt-10400.torchjit"
speaker_id = 1

[[speakers]]
name = "Bill Gates (Multi-speaker model)"
slug = "glow-multi-gates"
model_pipeline = "ArpabetGlowTtsMultiSpeakerMelgan"
glow_tts_multi_speaker = "glow_tts_multispeaker_8-speaker_256-gin_ljs_txlearn_2020.06.19_experiment-5_chkpt-7466.torchjit"
melgan = "melgan_vocodes1.0_multispeaker_2020.06.19_12d5838_experiment-2_chkpt-10400.torchjit"
speaker_id = 2

[[speakers]]
name = "Arnold Schwarzenegger (Multi-speaker model)"
slug = "glow-multi-arnold"
model_pipeline = "ArpabetGlowTtsMultiSpeakerMelgan"
glow_tts_multi_speaker = "glow_tts_multispeaker_8-speaker_256-gin_ljs_txlearn_2020.06.19_experiment-5_chkpt-7466.torchjit"
melgan = "melgan_vocodes1.0_multispeaker_2020.06.19_12d5838_experiment-2_chkpt-10400.torchjit"
speaker_id = 3

[[speakers]]
name = "Ronald Reagan (Multi-speaker model)"
slug = "glow-multi-reagan"
model_pipeline = "ArpabetGlowTtsMultiSpeakerMelgan"
glow_tts_multi_speaker = "glow_tts_multispeaker_8-speaker_256-gin_ljs_txlearn_2020.06.19_experiment-5_chkpt-7466.torchjit"
melgan = "melgan_vocodes1.0_multispeaker_2020.06.19_12d5838_experiment-2_chkpt-10400.torchjit"
speaker_id = 4

# --------------- Model configs ---------------

[[model_locations]]
model_type = "ArpabetGlowTts"
base_directory = "/data/downloads/downloaded/models/glow-tts-jaywalnut/"

[[model_locations]]
model_type = "Melgan"
base_directory = "/data/downloads/downloaded/models/melgan-swpark/"


# ---------------- Glow TTS----------------

[[glow_tts]]
file_path = "glow_tts_ljs_txlearn_arpabet_2020-06-01_G_1689-2.torchjit"
description = "First experiments in glow-tts (continued); the '-2' is longer JIT tracing input"

# ---------------- Melgan ----------------

[[melgan]]
file_path = "melgan_trump_txlearn_2020-05-30_steno_chkpt9800.torchjit"
description = "Trump steno data"

[[melgan]]
file_path = "melgan_vocodes1.0_multispeaker_2020.06.19_12d5838_experiment-2_chkpt-10400.torchjit"
description = "First round of multi-speaker experiments for glow-tts"
