[[speakers]]
name = "Craig Ferguson"
slug = "craig-ferguson"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_craig_ferguson_ljstx_2020.07.13_expr-1_chkpt-7680.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "Bryan Cranston"
slug = "bryan-cranston"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_bryan_cranston_ljstx_2020.07.13_expr-1_chkpt-7795.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "Neil deGrasse Tyson"
slug = "neil-degrasse-tyson"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_neil_degrasse_tyson_ljstx_2020.07.05_expr-1_chkpt-2482.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "Hillary Clinton"
slug = "hillary-clinton"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_hillary_clinton_ljstx_2020.07.15_expr-2_chkpt-7250.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "James Earl Jones"
slug = "james-earl-jones"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_james_earl_jones_ljstx_2020.07.07_expr-1_chkpt-2573.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "Arnold Schwarzenegger"
slug = "arnold-schwarzenegger"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_arnold_schwarzenegger_ljstx_2020.07.16_expr-2_chkpt-9045.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "David Cross"
slug = "david-cross"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_david_cross_ljstx_2020.07.13_expr-1_chkpt-9462.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "George Takei"
slug = "george-takei"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_george_takei_ljstx_2020.07.08_expr-1_chkpt-4060.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "Judi Dench"
slug = "judi-dench"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_judi_dench_ljstx_2020.07.08_expr-1_chkpt-4693.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

[[speakers]]
name = "George W. Bush"
slug = "george-w-bush"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_george_w_bush_ljstx_2020.06.26_expr-1_chkpt-1735.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_10090.torchjit"

# ---

[[speakers]]
name = "Bill Nye"
slug = "bill-nye"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_bill_nye_ljstx_2020.07.07_expr-1_chkpt-2510.torchjit"
melgan = "melgan_manyvoice2.0_2020-07-08_12d5838_9330.torchjit"

[[speakers]]
name = "Jimmy Carter"
slug = "jimmy-carter"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_jimmy_carter_ljstx_2020.07.05_expr-1_chkpt-2391.torchjit"
melgan = "melgan_manyvoice2.0_2020-07-08_12d5838_9330.torchjit"

[[speakers]]
name = "Richard Nixon"
slug = "richard-nixon"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_richard_nixon_ljstx_2020.07.08_expr-1_chkpt-3847.torchjit"
melgan = "melgan_manyvoice2.0_2020-07-08_12d5838_8940.torchjit"

[[speakers]]
name = "Sir David Attenborough"
slug = "david-attenborough"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_david_attenborough_ljstx_2020.07.05_expr-1_chkpt-2446.torchjit"
melgan = "melgan_manyvoice2.0_2020-07-08_12d5838_8940.torchjit"

[[speakers]]
name = "Bill Clinton"
slug = "bill-clinton"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_bill_clinton_ljstx_2020.06.28_expr-1_chkpt-1659.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"

[[speakers]]
name = "Christopher Lee"
slug = "christopher-lee"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_christopher_lee_ljstx_2020.06.28_expr-1_chkpt-4100.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"

[[speakers]]
name = "Barack Obama (needs work)"
slug = "barack-obama"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_barack_obama_ljstx_2020.06.28_expr-1_chkpt-1729.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"
sample_rate_hz = 22000 # This is lower than normal

[[speakers]]
name = "Betty White (needs work)"
slug = "betty-white"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_betty_white_ljstx_2020.06.28_expr-1_chkpt-1666.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"

[[speakers]]
name = "Dr. Phil McGraw"
slug = "dr-phil-mcgraw"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_dr_phil_mcgraw_ljstx_2020.06.28_expr-1_chkpt-1813.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"

[[speakers]]
name = "Fred Rogers"
slug = "fred-rogers"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_fred_rogers_ljstx_2020.06.28_expr-1_chkpt-2575.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"

[[speakers]]
name = "Danny Devito"
slug = "danny-devito"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_danny_devito_ljstx_2020.06.28_expr-1_chkpt-3757.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"


[[speakers]]
name = "Donald Trump"
slug = "donald-trump"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow_tts_ljs_txlearn_arpabet_2020-06-01_G_1689-2.torchjit"
melgan = "melgan_trump_txlearn_2020-05-30_steno_chkpt9800.torchjit" # Bespoke melgan
sample_rate_hz = 21000 # This is lower than normal

[[speakers]]
name = "Gilbert Gottfried"
slug = "gilbert-gottfried"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_gilbert-gottfried_ljstx_2020.06.28_expr-1_chkpt-1766.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"

[[speakers]]
name = "Ronald Reagan"
slug = "ronald-reagan"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_solo_reagan_ljstx_2020.06.22_expr-1_chkpt-1406.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"
sample_rate_hz = 21000 # This is lower than normal

[[speakers]]
name = "John Oliver"
slug = "john-oliver"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_solo_oliver_ljstx_2020.06.22_expr-1_chkpt-1189.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"
sample_rate_hz = 21000 # This is lower than normal

[[speakers]]
name = "Bill Gates"
slug = "bill-gates"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_solo_billgates_ljstx_2020.06.24_expr-1_chkpt-2011.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"

[[speakers]]
name = "Mark Zuckerberg"
slug = "mark-zuckerberg"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_solo_zuckerberg_ljstx_2020.06.24_expr-1_chkpt-2280.torchjit"
melgan = "melgan_manyvoice1.0_2020-06-28_12d5838_7050.torchjit"
sample_rate_hz = 21000 # This is lower than normal

[[speakers]]
name = "Tupac Shakur"
slug = "tupac-shakur"
model_pipeline = "ArpabetGlowTtsMelgan"
glow_tts = "glow-tts_tupac_shakur_ljstx_2020.07.16_expr-2_chkpt-6341.torchjit"
melgan = "melgan_manyvoice3.0_2020-07-17_12d5838_9920.torchjit"

# --------------- Model configs ---------------

[[model_locations]]
model_type = "ArpabetGlowTts"
prod_base_directory = "/data/downloads/downloaded/models/glow-tts-jaywalnut/"

[[model_locations]]
model_type = "ArpabetGlowTtsMultiSpeaker"
prod_base_directory = "/data/downloads/downloaded/models/glow-tts-jaywalnut-multispeaker/"

[[model_locations]]
model_type = "Melgan"
prod_base_directory = "/data/downloads/downloaded/models/melgan-swpark/"
