[package]
name = "elasticsearch_schema"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[lib]
name = "elasticsearch_schema"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
enums = { workspace = true }
errors = { workspace = true }
tokens = { workspace = true }

# External
elasticsearch = { version = "8.5.0-alpha.1", default-features = false, features = ["rustls-tls"] }
jsonpath_lib = "0.3.0"
log = "0.4.14"
once_cell = "1.19.0"

# Serialization
chrono = { version = "0.4.22", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.108"

[dev-dependencies]
# None yet