[package]
name = "tts-download-job"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "tts-download-job"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]

# Internal
bucket_paths = { path = "../../../lib/bucket_paths" }
cloud_storage.workspace = true
config = { path = "../../../lib/deprecated/config" }
easyenv = { path = "../../../lib/easyenv" }
enums.workspace = true
errors.workspace = true
filesys.workspace = true
google_drive_common = { path = "../../../api_clients/google_drive_common" }
hashing = { path = "../../../lib/files/hashing" }
jobs_common = { path = "../../../lib/jobs_common" }
mysql_queries = { path = "../../../schema/database/mysql_queries" }

# Workspace hack (faster compile times)
workspace-build-acceleration = { version = "0.1", path = "../../../workspace-build-acceleration" }

# External
anyhow.workspace = true
chrono.workspace = true
dotenv = "0.15.0"
hostname = "0.4.0"
log.workspace = true
subprocess = "0.2.9"
tempdir.workspace = true

sqlx = { version = "0.7.2", features = [ "mysql", "runtime-tokio", "tls-rustls", "chrono" ] }

# Redis
r2d2_redis = "0.14.0"

# Runtime
tokio.workspace = true

# NB: Hyper is just for HTTP client use in jobs. I'd use Actix client, but I need tokio runtime
# NB: Furthermore, the Tokio runtime is old, so I have to use an older Hyper.
hyper = { version = "1.3.1" }

# Serialization
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
