[package]
name = "aichatbot-sidecar"
publish = false
edition = "2021"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]

[[bin]]
name = "aichatbot-sidecar"
path = "src/main.rs"

[dependencies]

# Internal
actix_helpers = { path = "../../lib/actix_helpers" }
concurrency = { path = "../../lib/concurrency" }
enums = { path = "../../_types/enums" }
errors = { path = "../../lib/errors" }
fakeyou_client = { path = "../../lib/fakeyou_client" }
files = { path = "../../lib/files" }
hashing = { path = "../../lib/hashing" }
http_server_common = { path = "../../lib/http_server_common" }
idempotency = { path = "../../lib/idempotency" }
media = { path = "../../lib/media" }
sqlite_queries = { path = "../../lib/sqlite_queries" }
tokens = { path = "../../_types/tokens" }
web_scrapers = { path = "../../lib/web_scrapers" }

# External
chrono = { version = "0.4.19", features = ["serde"] }
clap = "2.34.0" # TODO: This is really out of date, but has conflicts when updated
dotenv = "0.15.0"
easyenv = "0.0.6"
log = "0.4.14"
once_cell = "1.9.0"
path-absolutize = "3.0.14" # Absolute paths have not stabilized in Rust yet
regex = "1.5.4"
strum = { version = "0.24", features = ["derive"] } # Fancy enum iteration, etc.

# SQlite Database
# "offline" supports typesafe builds without a live database
# "rustls" doesn't appear to work with IP addresses, per:
# https://github.com/launchbadge/sqlx/issues/1095#issuecomment-798050828
#  ^^^ Granted, this applies to *MySQL* and probably not SQLite for our use case here ^^^
sqlx = { version = "0.6.2", features = [ "sqlite", "runtime-actix-native-tls", "offline", "chrono" ] }

# Async Runtime
tokio = { version = "1.6.0", features = ["macros"] }

# Content downloads
reqwest = { version = "0.11", features = ["json"] } # HTTP Client
rss = "2.0.2"

# Webserver
actix-cors = "0.6.0-beta.3"
actix-files= "0.6.0-beta.8"
actix-http = "3.0.0-beta.11"
actix-multipart = "0.4.0-beta.7"
actix-rt = "2.4.0"
actix-service = "2.0.1"
actix-utils = "3.0.0"
actix-web = "4.0.0-beta.10"
actix-web-actors = "4.0.0-beta.7"

# Serialization
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
serde_yaml = "0.9.1"

# Gui (Egui)
eframe = "0.20.1"
egui = "0.20.1"

# API integrations
async-openai = "0.6.0"
