[package]
name = "aichatbot-sidecar"
publish = false
edition = "2021"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]

[[bin]]
name = "aichatbot-sidecar"
path = "src/main.rs"

[dependencies]

# Internal
errors = { path = "../../lib/errors" }
http_server_common = { path = "../../lib/http_server_common" }

# External
clap = "2.34.0" # TODO: This is really out of date, but has conflicts when updated
easyenv = "0.0.6"
log = "0.4.14"

# Async Runtime
tokio = { version = "1.6.0", features = ["macros"] }

# Gui (Egui)
eframe = "0.20.1"
egui = "0.20.1"

# Gui (Imgui)
imgui = "0.10.0"
glium = { version = "0.32.1", default-features = true }
imgui-glium-renderer = "0.10.0"
imgui-winit-support = "0.10.0"


# Web
actix-cors = "0.6.0-beta.3"
actix-files= "0.6.0-beta.8"
actix-http = "3.0.0-beta.11"
actix-multipart = "0.4.0-beta.7"
actix-rt = "2.4.0"
actix-service = "2.0.1"
actix-utils = "3.0.0"
actix-web = "4.0.0-beta.10"
actix-web-actors = "4.0.0-beta.7"

# Serialization
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
