[package]
name = "thumbnail_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# External
easyenv = { path = "../../lib/easyenv" }
log.workspace = true
reqwest.workspace = true
serde_json.workspace = true
