[package]
name = "reusable_types"
publish = false
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]

[lib]
name = "reusable_types"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
# (none)

# External
chrono = { workspace = true }

# Serialization
serde = { workspace = true }
serde_derive = { workspace = true }

# MySql Database
sqlx = { version = "0.7.4", default-features = false, features = [ "mysql", "runtime-tokio-rustls", "chrono" ] }
sqlx-core = { version = "0.7.4", features = ["rustls"] }

[dev-dependencies]
# Test serialization
toml = { workspace = true }
