[package]
name = "dev-upload-media-file"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "dev-upload-media-file"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
bucket_paths = { path = "../../../lib/bucket_paths" }
cloud_storage.workspace = true
config = { path = "../../../lib/deprecated/config" }
easyenv = { path = "../../../lib/easyenv" }
enums.workspace = true
errors.workspace = true
filesys.workspace = true
mimetypes.workspace = true
mysql_queries = { path = "../../../schema/database/mysql_queries" }
tokens.workspace = true

# External
clap = "4.4.8"
log.workspace = true

# Runtime
# NB: We switched to Tokio from `async-std` for broader ecosystem support.
tokio.workspace = true

sqlx = { version = "0.7.2", features = [ "mysql", "runtime-tokio", "tls-rustls", "chrono" ] }

[dev-dependencies]
# None yet
