# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "_ignored_schema.rs"

# I want to sort this directory first for easier reference
# Not released yet, but added here:
# https://github.com/diesel-rs/diesel/pull/2179
# You'll need to install the a non-released diesel CLI
# (See storyteller READMEs/docs on how to install)
[migrations_directory]
dir = "_migrations"
