[package]
name = "artcraft_api_defs"
edition = "2024"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[lib]
name = "artcraft_api_defs"
path = "src/lib.rs"

[dependencies]
# Hackari workspace (faster compile times)
workspace-build-acceleration.workspace = true

# Internal
enums.workspace = true
enums_public.workspace = true
tokens.workspace = true

# External
chrono.workspace = true
url.workspace = true

# Serialization
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true

utoipa = { version = "4", features = ["chrono", "actix_extras"] }

[dev-dependencies]
