[package]
name = "sqlite_tasks"
edition = "2024"
version = "0.0.1"
publish = false

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[lib]
name = "sqlite_tasks"
path = "src/lib.rs"

[dependencies]
# cargo-hakari workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# Internal
enums.workspace = true
errors.workspace = true
tokens.workspace = true

# External
anyhow.workspace = true
chrono.workspace = true
log.workspace = true

# TODO(bt,2025-07-09): Update sqlx ASAP. We're stuck on 0.7 because of the complex use of internal types and macros in the database crate.
# We're going to embed in-memory SQLite
sqlx = { package = "sqlx", version = "0.7.4", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }

# Needed to safety check some queries we can't use escaping for
once_cell.workspace = true
regex.workspace = true

# Serialization
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true

[dev-dependencies]
# serial_test = "3.0.0"

[build-dependencies]
tempfile.workspace = true
sqlx = { package = "sqlx", version = "0.7.4", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }
#rusqlite = "0.25.4" # NB: For the build.rs file
