[package]
name = "db-cleanup"
publish = false
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]

[[bin]]
name = "db-cleanup"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
bucket_paths = { path = "../../../lib/bucket_paths" }
easyenv = { path = "../../../lib/easyenv" }
enums = { path = "../../../schema/public/enums" }
errors = { path = "../../../lib/errors" }
mysql_queries = { path = "../../../schema/database/mysql_queries" }
storyteller_root = { path = "../../../lib/storyteller_root" }
tokens = { path = "../../../schema/public/tokens" }

# External
clap = "4.4.8"
dotenv = "0.15.0"
itertools = "0.13.0"
log = "0.4.14"

# Bigger pieces
tokio = { version = "1.38.0", features = ["macros"] }
sqlx = { version = "0.7.4", features = [ "mysql", "runtime-tokio-rustls", "chrono" ] }

# Serialization
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.108"

[dev-dependencies]
# None yet
