[package]
name = "inference-job"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "inference-job"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# cargo-hakari workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# Internal
actix_helpers = { path = "../../../lib/actix_helpers" }
bootstrap = { path = "../../../lib/bootstrap" }
bucket_paths = { path = "../../../lib/bucket_paths" }
cloud_storage.workspace = true
collections = { path = "../../../lib/data/collections" }
composite_identifiers = { path = "../../../schema/public/composite_identifiers" }
concurrency = { path = "../../../lib/concurrency" }
config = { path = "../../../lib/deprecated/config" }
crockford.workspace = true
easyenv = { path = "../../../lib/easyenv" }
enums.workspace = true
errors.workspace = true
filesys.workspace = true
google_drive_common = { path = "../../../api_clients/google_drive_common" }
hashing = { path = "../../../lib/files/hashing" }
images.workspace = true
jobs_common = { path = "../../../lib/jobs_common" }
media = { path = "../../../lib/files/media" }
memory_caching = { path = "../../../lib/caching/memory_caching" }
migration = { path = "../../../lib/migration" }
mimetypes = { path = "../../../lib/files/mimetypes" }
mysql_queries = { path = "../../../schema/database/mysql_queries" }
openai_sora_client = { path = "../../../api_clients/openai_sora_client" }
primitives.workspace = true
redis_common = { path = "../../../schema/database/redis_common" }
redis_schema = { path = "../../../schema/database/redis_schema" }
shared_service_components = { workspace = true }
subprocess_common = { path = "../../../lib/subprocess_common" }
thumbnail_generator = { path = "../../../api_clients/thumbnail_generator"}
tokens.workspace = true
tts_common = { path = "../../../lib/tts_common" }
videos = { path = "../../../lib/files/videos" }

# External
anyhow.workspace = true
chrono.workspace = true
dotenv = "0.15.0"
hostname = "0.4.0"
lfu = "0.2.5"
log.workspace = true
once_cell.workspace = true
subprocess = "0.2.9"
tempdir.workspace = true

sqlx = { version = "0.7.4", features = [ "mysql", "runtime-tokio", "tls-rustls", "chrono" ] }

# Redis
r2d2_redis = "0.14.0"

# Runtime
# NB: We switched to Tokio from `async-std` for broader ecosystem support.
tokio = { version = "1.40.0", features = ["macros", "sync"] }
tokio-util = "0.7.12"
tokio-stream = "0.1.16"

# HTTP Client
reqwest = { version = "0.12.4", features = ["blocking"] }

# HTTP Server
actix-web.workspace = true

# Serialization
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true

# Async traits
# NB: note: `async` trait functions are not currently supported
# The initial round of stabilizations for the async/await language feature in Rust 1.39 did not
# include support for async fn in traits.
async-trait = "0.1.58"
time = "0.3.30"
mime = "0.3.17"
rand = { version = "0.8.5", features = [] }
jsonpath_lib = "0.3.0"
walkdir = "2.4.0"
opentelemetry = {version = "0.23.0", features = ["metrics"]}
opentelemetry-otlp = { version = "0.16.0", features = ["metrics"] }
opentelemetry_sdk = { version = "0.23.0", features = ["metrics", "rt-tokio"] }
zip = "2.1.3"
url = { workspace = true }

[dev-dependencies]
testing = { path = "../../../lib/testing" }
