[package]
name = "migration-tool"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "migration-tool"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# Internal
bucket_paths = { path = "../../../lib/bucket_paths" }
cloud_storage.workspace = true
config = { path = "../../../lib/deprecated/config" }
easyenv = { path = "../../../lib/easyenv" }
enums.workspace = true
errors.workspace = true
filesys.workspace = true
hashing = { path = "../../../lib/files/hashing" }
mysql_queries = { path = "../../../schema/database/mysql_queries" }
storyteller_root = { path = "../../../lib/storyteller_root" }
tokens.workspace = true

# External
clap = "4.4.8"
log.workspace = true
strum = { version = "0.26", features = ["derive"] }
tempdir.workspace = true

# Async + clients
tokio.workspace = true
sqlx = { version = "0.7.4", features = [ "mysql", "runtime-tokio-rustls", "chrono" ] }

# Serialization
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true

[dev-dependencies]
# None yet
