[package]
name = "composite_identifiers"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[lib]
name = "composite_identifiers"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
enums = { workspace = true }
tokens = { workspace = true }


# Serialization
serde = "1.0.125"
serde_derive = "1.0.125"

sqlx = { version = "0.7.4", features = [ "mysql", "sqlite", "runtime-tokio-native-tls", "chrono" ] }
sqlx-core = { version = "0.7.4" }
sqlx-mysql= { version = "0.7.4" }

utoipa = { version = "4", features = ["chrono","actix_extras"] }

[dev-dependencies]

# Test serialization
serde_json = "1.0.108"
