[package]
name = "runwayml_client"
edition = "2021"
version = "0.0.1"
publish = false

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[lib]
name = "runwayml_client"
path = "src/lib.rs"

[dependencies]

# Workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# Internal
crockford.workspace = true
errors.workspace = true
idempotency.workspace = true
jwt_light.workspace = true
subprocess_common = { path = "../../lib/subprocess_common" }

# External
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
cookie.workspace = true
hex-literal.workspace = true
log.workspace = true
once_cell.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
sha3.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
testing = { path = "../../lib/testing" }
filesys.workspace = true
