# A list of statically-configured (not-DB backed) API tokens.
# This file is *NOT* distributed with the docker image and is just an example for local development.

# kubectl create configmap static-api-tokens --namespace storyteller --from-file=static_api_tokens.toml

#[[api_tokens]]
#api_token = 'foo'
#maybe_user_token = 'FOO'
#maybe_priority_level = 3

# /profile/api_edymuro (EdyMuro#8205)
# Requested 2022-04-18 in Discord chat with Vegito
# Using for their own mobile TTS app.
[[api_tokens]]
api_token = "SAPI:EDYMURO_A648684D5C6FDCFD"
maybe_user_token = 'U:VR4HNTYCDBR9W'

# /profile/api_ftk789 (ftk789#7898)
# Twitch TTS / Moderator
# Requested 2022-04-27
[[api_tokens]]
api_token = "SAPI:FTK789_6096133E1D79D6FB"
maybe_user_token = 'U:0S09H086R6TRH'

# /profile/Hmm (ID10T#6255)
# Requested 2022-04-29 in Discord
# Using for their own mobile TTS app.
[[api_tokens]]
api_token = "SAPI:HMM_7B3CFC9D64A90006"
maybe_user_token = 'U:B2MQPN6ZGAXH5'

# /profile/majd (Majd#3540)
# Requested 2022-05-01 in Discord
# For Elon Musk + Unity experiment
[[api_tokens]]
api_token = "SAPI:MAJD_0001A330EC41FB6D"
maybe_user_token = 'U:WSKSXDAZVXY5W'

## /profile/api_duke (Duke#4009)
## Wants this for a Hackathon but "won't pay".
## Update: Cancelled hackathon
#[[api_tokens]]
#api_token = "API:TEMPORARY_DUKE_97FA10"
#maybe_user_token = 'U:D3TR4XRJZ3K3R'
