[[redirects]]
  from = "https://storyteller.company"
  to = "https://the.storyteller.company"
  status = 302
  force = true

[[redirects]]
  from = "https://www.storyteller.company"
  to = "https://the.storyteller.company"
  status = 302
  force = true

