[package]
name = "redis_schema"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[lib]
name = "redis_schema"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
enums = { workspace = true }
errors = { workspace = true }
tokens = { workspace = true }

# External
chrono = { workspace = true }

# Redis
r2d2_redis = "0.14.0"
url = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
# None yet
