# The base URL of the site; the only required configuration variable.
base_url = "/"

# The site title and description; used in feeds by default.
title = "Storyteller.ai"
description = "Blog posts and tutorials of Storyteller.ai"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
# theme = "kita"   
# Our theme is based on Kita, but we need so much customization that we dont use any theme directly

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#

taxonomies = [
  { name= "featured", feed = true, paginate_by = 5},
  { name= "categories", paginate_by = 5},
  { name = "tags", rss = true, paginate_by = 5 },
  { name = "authors", paginate_by = 5 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
social_image = "icons/github.svg"

