[package]
name = "websocket-gateway"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "websocket-gateway"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["my-workspace-hack"]

[dependencies]

# Internal
actix_cors_configs = { path = "../../../lib/actix_cors_configs" }
config = { path = "../../../lib/deprecated/config" }
container_common = { path = "../../../lib/deprecated/container_common" }
easyenv = { path = "../../../lib/easyenv" }
errors = { path = "../../../lib/errors" }
http_server_common = { path = "../../../lib/deprecated/http_server_common" }
mysql_queries = { path = "../../../lib/mysql_queries" }
redis_common = { path = "../../../lib/redis_common" }
twitch_common = { path = "../../../lib/api_clients/twitch_common" }

# Workspace hack (faster compile times)
my-workspace-hack = { version = "0.1", path = "../../../my-workspace-hack" }

# External
anyhow = "1.0.86"
base64 = "0.22.1"
chrono = { version = "0.4.22", features = ["serde"] }
derive_more = "0.99.17"
dotenv = "0.15.0"
hostname = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8.5"
regex = "1.5.4"
time = "0.3.30"
uuid = { version = "1.8.0", features = ["v4"] }

# Runtime
# NB: We switched to Tokio from `async-std` for broader ecosystem support.
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros", "time"] }

# Futures
futures = { version = "0.3.17", features = ["thread-pool"] } # feature for ThreadPool
futures-util = "0.3.29"
futures_old_for_limiter = { package = "futures", version = "0.1.29" } # Older version of futures for `limiter` crate

sqlx = { version = "0.7.2", features = [ "mysql", "runtime-tokio", "tls-rustls", "chrono" ] }

# Redis Database
limitation = { path = "../../../vendor/limitation" }
r2d2_redis = "0.14.0"
redis_async = { package = "redis", version = "0.21.5", features = ["tokio-comp"] }

# Twitch
# NB "unsupported" pubsub features may disappear from the Twitch API at any time. It's an unofficial API.
twitch_api2 = { version = "0.6.0-rc.2", features = ["helix", "reqwest_client", "pubsub", "chrono", "unsupported"] }
twitch_oauth2 = "0.6.0-rc.2"

# HTTP
reqwest = { version = "0.11.4" }
native-tls = "0.2.8"

# Web
actix = "0.13.5"
actix-cors = "0.6.4"
actix-files= "0.6.6"
actix-http = "3.7.0"
actix-rt = "2.10.0"
actix-service = "2.0.2"
actix-utils = "3.0.1"
actix-web = "4.7.0"
actix-web-actors = "4.3.0"

# NB: Hyper is just for HTTP client use in jobs. I'd use Actix client, but I need tokio runtime
# NB: Furthermore, the Tokio runtime is old, so I have to use an older Hyper.
hyper = { version = "0.14.24" }

# Crypto
magic-crypt = "3.1.13" # encrypting sort IDs for the frontend so we don't leak info
md-5 = "0.10.6" # gravatar
sha2 = "0.9.9" # file hashes, inference text hashes, etc.

# Serialization
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.108"
toml = "0.8.14"

[build-dependencies]
# NB: Only using diesel for migrations support
diesel = { version = "2.1.3", features = ["mysql"] }
