[package]
name = "dummy-service"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "dummy-service"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]

# Internal
actix_cors_configs = { path = "../../../lib/actix_cors_configs" }
actix_helpers = { path = "../../../lib/actix_helpers" }
easyenv = { path = "../../../lib/easyenv" }
errors = { path = "../../../lib/errors" }
reusable_types = { path = "../../../schema/public/reusable_types" }

# Workspace hack (faster compile times)
workspace-build-acceleration = { version = "0.1", path = "../../../workspace-build-acceleration" }

# External
chrono = { version = "0.4.22", features = ["serde"] }
dotenv = "0.15.0"
hostname = "0.4.0"
#once_cell = "1.9.0"
#regex = "1.5.4"

# Runtime
# NB: We switched to Tokio from `async-std` for broader ecosystem support.
tokio = { version = "1.38.0", features = ["macros"] }

# Futures
futures-util = "0.3.29"

# Web
actix-http = "3.7.0"
actix-rt = "2.10.0"
actix-service = "2.0.2"
actix-utils = "3.0.1"
actix-web = "4.7.0"

# Serialization
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.108"
