[package]
name = "dummy-service"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "dummy-service"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
actix_cors_configs = { path = "../../../lib/actix_cors_configs" }
actix_helpers = { path = "../../../lib/actix_helpers" }
easyenv = { path = "../../../lib/easyenv" }
errors = { workspace = true }
reusable_types = { path = "../../../schema/public/reusable_types" }

# External
chrono = { workspace = true }
dotenv = "0.15.0"
hostname = "0.4.0"

# Runtime
# NB: We switched to Tokio from `async-std` for broader ecosystem support.
tokio = { version = "1.38.0", features = ["macros"] }

# Futures
futures-util = "0.3.29"

# Web
actix-http = { workspace = true }
actix-rt = { workspace = true }
actix-service = { workspace = true }
actix-utils = { workspace = true }
actix-web = { workspace = true }

# Serialization
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
