[package]
name = "dummy-service"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "dummy-service"
path = "src/main.rs"

[dependencies]

# Internal
actix_helpers = { path = "../../../lib/actix_helpers" }
easyenv = { path = "../../../lib/easyenv" }
errors = { path = "../../../lib/errors" }
reusable_types = { path = "../../../_types/reusable_types" }

# External
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
hostname = "0.3.1"
#once_cell = "1.9.0"
#regex = "1.5.4"

# Runtime
# NB: We switched to Tokio from `async-std` for broader ecosystem support.
tokio = { version = "1.6.0", features = ["macros"] }

# Futures
futures-util = "0.3.29"

# Web
actix-http = "3.4.0"
actix-rt = "2.9.0"
actix-service = "2.0.1"
actix-utils = "3.0.0"
actix-web = "4.0.0-beta.10"

# Serialization
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.108"
my-workspace-hack = { version = "0.1", path = "../../../../my-workspace-hack" }
