[package]
name = "email-sender-job"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[[bin]]
name = "email-sender-job"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
actix_helpers = { path = "../../../lib/actix_helpers" }
bootstrap = { path = "../../../lib/bootstrap" }
concurrency = { path = "../../../lib/concurrency" }
config = { path = "../../../lib/deprecated/config" }
easyenv = { path = "../../../lib/easyenv" }
email_sender = { path = "../../../lib/email_sender" }
enums = { workspace = true }
errors = { workspace = true }
filesys = { path = "../../../lib/files/filesys" }
jobs_common = { path = "../../../lib/jobs_common" }
mysql_queries = { path = "../../../schema/database/mysql_queries" }
server_environment = { path = "../../../lib/server_environment" }

# External
anyhow = { workspace = true }
log = { workspace = true }

sqlx = { version = "0.7.2", features = [ "mysql", "runtime-tokio", "tls-rustls", "chrono" ] }

# Redis
r2d2_redis = "0.14.0"

# HTTP Server
actix-web = { workspace = true }

# Serialization
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
