[package]
name = "ml_weights_registry"
edition = "2021"
version = "0.0.1"
authors = ["storyteller"]
publish = false
description = ""
license = ""
repository = ""

[lib]
name = "ml_weights_registry"
path = "src/lib.rs"

# External
[dependencies]
anyhow = "1.0"
const_format = "0.2.34"
