# This action syncs "staging" with "master" by force pushing every time it is run.
# Adapted from: 
# https://github.community/t/user-github-pages-site-auto-deploy-from-another-branch-on-push/17912/2
on:
  push:
    branches:
      - master

jobs:
  sync_staging_branch:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout master branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: sync master to staging
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b staging
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          # Note: Github does not allow the default access token to push to 
          # protected branches. Using a PAT with permissions can bypass this, 
          # but it triggers recursive Github Actions calls on branch updates
          # (which the default access token does not). Ultimately, it's better
          # to leave the staging branch unprotected.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          force: true
